title: Tolga Buyuktanir's Homepage
page-top-title: Tolga Buyuktanir
top-section-bg-text: Yildiz Technical University Computer Engineering Department
home-subtitle: Tolga Buyuktanir&ensp;
copyright-text: '&copy; Tolga Buyuktanir 2024-2025. All Rights Reserved.'
